obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.22,0.22], [0.22,-0.22],[-0.22,-0.22],[-0.22,0.22]]
#robot_radius: ir_of_robot
inflation_radius: 0.22

observation_sources: point_cloud_sensor laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_range_sensor_link , data_type: LaserScan, topic: /hsrb/base_scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: head_rgbd_sensor_depth_frame , data_type: PointCloud2, topic: /hsrb/head_rgbd_sensor/depth_registered/rectified_points, marking: true, clearing: true}
